-- AlterTable
ALTER TABLE "Attendance" ALTER COLUMN "clockIn" SET DATA TYPE TEXT,
ALTER COLUMN "clockOut" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Shift" ALTER COLUMN "clockIn" SET DATA TYPE TEXT,
ALTER COLUMN "clockOut" DROP NOT NULL,
ALTER COLUMN "clockOut" SET DATA TYPE TEXT;
